### PR TITLE
updated elcid requirements for Opal 0.10.0

### PR DESCRIPTION
**Pull request by pacharanero**

### CODE REVIEW

**Comment by pacharanero** [comment]
closes #1551

**Comment by pacharanero** [comment]
the failures in the Travis build are fixed in 0.7.1 https://github.com/openhealthcare/elcid/pull/1559

**Comment by pacharanero** [comment]
@fredkingham I'm not sure why this is still failing to build - the fix you pushed for datestamps in Elcid eariler should have fixed this? Is Travis still using an older version?

the errors in the JS tests are similar:
```
EXPECTED: {"end":"19/03/2018","id":33}
	GOT:      {"id":33,"start":null,"end":"19/03/2018"} in lib/bower_components/angular-mocks/angular-mocks.js (line 1385)
```

**Comment by fredkingham** [comment]
@pacharanero so this is still failing as v0.7.1 has to be merged back into it. That's why the second test passes as this is the test of the two branches integrated, but the first fails.

That said I merged https://github.com/openhealthcare/elcid/pull/1558 so I don't understand why this branch is still showing that there are things to merge. Do you?

(If not I'm tempted to close this)

**Comment by pacharanero** [comment]
Yes that's what I couldn't work out - you have merged the fix so I can't see why the build continues to fail, unless perhaps it is 'pinned' to a specific commit?

I'm all for merging since we are sure it's fixed in 0.7.1. It's a very small commit and there's nothing in this PR that would have conceivably affected the date/time stamping.

**Comment by fredkingham** [comment]
I've merged v0.7.1 into 1551-update-elcid-requirements-for-new-0.10-updates and now there are no diffs. Closing this.

**Pull request closed without merging**
